version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_CONNECTION: "sqlite:///student.db"  # SQLite connection string
    volumes:
      - ./student.db:/app/student.db  # Mount SQLite database file into the container
